enum CashTransactionType {
    INCOME = 'INCOME',
    EXPENSE = 'EXPENSE',
    ASSET_TRANSFER = 'ASSET_TRANSFER',
    LIABILITY_TRANSFER = 'LIABILITY_TRANSFER',
    OPENING_NEGATIVE = 'OPENING_NEGATIVE',
    OPENING_POSITIVE = 'OPENING_POSITIVE',
    LIABILITY_INCREASE = 'LIABILITY_INCREASE',
    LIABILITY_DECREASE = 'LIABILITY_DECREASE',
}

export default CashTransactionType;
