enum WaitType {
    PREVIEW_ACCOUNT = 'PREVIEW_ACCOUNT',
    CHECK_ACCOUNT_DEP = 'CHECK_ACCOUNT_DEP',
    HOME_PAGE = 'HOME_PAGE',
    IMPORT_FILE_CONVERT_CSV = 'IMPORT_FILE_CONVERT_CSV',
    MULTI_EDIT_TRANSACTION = 'MULTI_EDIT_TRANSACTION',
    TIME_FRAME_DATA_FILL_ALL = 'TIME_FRAME_DATA_FILL_ALL',
    SAVE_TRANSACTION_LIST = 'SAVE_TRANSACTION_LIST',
}

export default WaitType;
